# netlify.toml
[functions]
# Specifies `esbuild` for functions bundling
node_bundler = "esbuild"
external_node_modules = [
    "next",
    "type-graphql",
    "require_optional",
    "typeorm",
    "app-root-path",
]
